# Numpy
It's short for Numerical Python
- [.methods()|Random|Distribution|uFunc](https://www.w3schools.com/python/numpy/numpy_array_reshape.asp)<br>
- [Detailed and Advanced](https://www.geeksforgeeks.org/numpy-tutorial/)<br>
- [all adv.methods in numpy](https://www.geeksforgeeks.org/python-numpy/)<br>

<br>

- **Basic exersises**
    - [Kaggle basic numpy problems](https://www.kaggle.com/code/themlphdstudent/learn-numpy-numpy-50-exercises-and-solution)
    - [101 Numpy Problems - machinelearningplus](https://www.machinelearningplus.com/python/101-pandas-exercises-python/)
<br>


## What is NumPy?
**Defination** : NumPy is used to perform mathamatical **opertations** and **manipulation** of a multi-dimentional array  
- python dosent support **array** directly that's why we use numpy.
- Numpy has only one data structure **array**
- Numpy is used for numeric data
- Default data type is **Float**



##  When to use array? 
- When you need to process faster.
- it's simillar to list with added functionality and reduced versitality.
- It can be accessed faster.


## Why use **array** and not **list**?

- For working with data we need to be faster than normal list.<br>
- Accessing elements in list is slow because ***list in python are a linked-list (not simple list)***,<br> This makes list slower.
- **LISTS** are **heterogenous**( it can contain all kinds of datatypes) **ARRAYS** are **homogenous**( can only contain one kind of datatype at a time).<br> This makes list versatile and slower.



## How to install and import "numpy"?

In [1]:
# to install the package | not to run everytime
# pip install numpy

In [2]:
# to import nad use numpy
import numpy as np # type: ignore

## How to Create array?
### 1. Array from list?

In [3]:

ls = [5,2,9,6,2,4,7,3,9] # this is a list

# method "array" of numpy(np) is given an argument variable "ls" which points to a list
# that list is converted to array
arr1 = np.array(ls) 
arr1

array([5, 2, 9, 6, 2, 4, 7, 3, 9])

### 2. Creating Array directly?

In [4]:
# directly giving a list as argument to 'array' method
arr2 = np.array([1,2,3,4]) 
arr2

# pay attention all elements are homogen

array([1, 2, 3, 4])

### 3. Input in array method is not homogenous?

In [5]:
# one of the elements is "float"
arr3 = np.array([1,2,3,4.7]) 
arr3



array([1. , 2. , 3. , 4.7])

> whole array is converted to float 
- as float can is capable to record both int and float value.

In [6]:
# one of the elements is "str"

arr3 = np.array([1,2,3,'3ri']) 
arr3

# whole array is converted to "str" 
# as str can is capable to record as int and float and str value.

array(['1', '2', '3', '3ri'], dtype='<U11')

> Data being convereted like this is also one of the disadvantages in numpy array as it will rarely through errors.

### 4. Using "arange()" to create array?
- SYNTAX : np.arange(start,stop,step)
> observe below ***array can be converted to matrix using .reshape()***

In [7]:
print( np.arange(4).reshape(2, 2))
print(np.arange(4, 10))
print(np.arange(4, 20, 3))

[[0 1]
 [2 3]]
[4 5 6 7 8 9]
[ 4  7 10 13 16 19]


### Creating array using **linspace()**?
- SYNTAX : np.linspace(start,end,elementCount)
- Used to create equidistant elements between two numbers

In [8]:
arrline = np.linspace(40,150,20)    #creating 20 equi-distant elements between 40 and 150
arrline

array([ 40.        ,  45.78947368,  51.57894737,  57.36842105,
        63.15789474,  68.94736842,  74.73684211,  80.52631579,
        86.31578947,  92.10526316,  97.89473684, 103.68421053,
       109.47368421, 115.26315789, 121.05263158, 126.84210526,
       132.63157895, 138.42105263, 144.21052632, 150.        ])

## How create array matrix?

In [9]:
arrMat = np.array([[2,5,2,3,4],[4,7,5,6,7]])
arrMat

array([[2, 5, 2, 3, 4],
       [4, 7, 5, 6, 7]])

## How to read an Matrix?
> after a   "**],**" read it as next row!

>case1

[[1,2,3], <br>
 [4,5,6]]

 &
 
 [[1,2,3],[4,5,6]]

both of these are the same


>case2

[[1],<br>
[2],<br>
[3]]

&

[[1],[2],[3]]

both of these are same

### Functions for kinds of matrix? 

Creates zero matrix

In [10]:
# np.zeros()?
zero = np.zeros((3,2))
zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

creates matrix with all ones

In [11]:
ones = np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Creates identity matrix

In [12]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a full matrix with a specific number
- SYNTAX : np.full((m,n),specific num)

In [13]:
sn = np.full((3,3),9)
sn

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

Create empty array

> it's not reliable rather full matrix with 0 as argument

In [14]:
empty = np.empty((2,2))
empty


array([[1. , 2. ],
       [3. , 4.7]])

In [15]:

empty2 = np.empty((3,3))
empty2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## + - * /  operators between matrices?
All these mathamatical operations can be performed on arrays of equal shape and size! 
- when discussing vectors in numpy or pandas we don't have a direction per say as in we used to discus in physics.
    -  here a 'scaler' is a uni-directional object. 
    - everything else is a vector if it has a n-dimentional (more than zero dimentions) i.e, a vector.


In [16]:
arr1 = np.arange(4, dtype = float).reshape(2, 2) 
 
print('First array:') 
print(arr1)
 
print('\nSecond array:') 
arr2 = np.array([12, 12]) 
print(arr2)
 


First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]


In [17]:
print('\nAdding the two arrays:')   # gives element wise addition as error
print(np.add(arr1, arr2))

 
print('\nSubtracting the two arrays:') 
print(np.subtract(arr1, arr2))
 
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))
 
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))


Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


## Concatination?

In [18]:
# case 1

# both a 2D array
arrC1 = np.array([[1,2],[3,4]])
arrC2 = np.array([[1,2]])   # attention!

# axis 0 means concatinate a row 
# axis 1 means concatinate a column

concatedArr = np.concatenate((arrC1, arrC2), axis = 0)      # adding a row
print(concatedArr)

[[1 2]
 [3 4]
 [1 2]]


In [19]:
# case 2
arrC1 = np.array([[1,2],[3,4]])
arrC2 = np.array([[1],[2]])   # attention!

concatedArr = np.concatenate((arrC1, arrC2), axis = 1)
print(concatedArr)

[[1 2 1]
 [3 4 2]]


## Shape in numpy? reshape?
- Dimention of matrix is it's shape i.e, (MxN)

In [20]:
from numpy import shape


Mat = np.arange(60) 
print(Mat)
print(shape(Mat)) # it's a 1D array so it's 1 dimention as output.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
(60,)


In [21]:
reshapedMat = Mat.reshape(5,12)
print(reshapedMat)
print(shape(reshapedMat)) # it's a 2D array so it's 2 dimention as output.

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59]]
(5, 12)


In [24]:
reshapedMat0 = Mat.reshape(20,3)
reshapedMat0

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [25]:
# if shape requested is not doable mathamatically it will give an error
reshapedMat1 = Mat.reshape(12,1)
reshapedMat1

ValueError: cannot reshape array of size 60 into shape (12,1)

## Size in numpy?
**Total elements in matrix = size of matrix**
- numpy.size() function counts the number of elements in a matrix

In [31]:
print(reshapedMat0)

# By default, give the total number of elements.
print(np.size(reshapedMat0))

#gives no. of rows along x-axis
print(np.size(reshapedMat0, 0)) 
 
#gives no. of columns along y-axis
print(np.size(reshapedMat0, 1)) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]
 [42 43 44]
 [45 46 47]
 [48 49 50]
 [51 52 53]
 [54 55 56]
 [57 58 59]]
60
20
3


### Resize?

#### Type1 : arr.resize(m,n)

- Cant be resized unresonably hence we will get error

In [41]:
ex=np.arange(6)
ex

array([0, 1, 2, 3, 4, 5])

In [44]:
ex.resize(1,2)      # resizing to less
ex

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [45]:
ex.resize(1,20)     # resizing to more
ex

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

#### Type2 : np.resize(arr,(m,n))
- Can resized unresonably as it removes and adds duplicate elements on it's own

In [48]:
ex = np.arange(6)
ex

array([0, 1, 2, 3, 4, 5])

In [50]:
np.resize(ex,(2))     # resizing to less

array([0, 1])

In [36]:
np.resize(ex,(5,5))     # resizing to more

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

### Reshape vs Resize?
- **Reshape** shows how a matrix will look like if it's diemntions where changed.
- **Resize** actually makes the changes at the memory level. 

## .ndim in numpy?
- tells us the dimensions of the array!

In [ ]:
# returns if it's 1D 2D 3D or more
arrMat.ndim

2

### .nbytes in numpy?
- tells us total number of bytes consuemed by the array

In [ ]:
arrMat.nbytes

40

### Change ndarray to 1darray using ravel()?
Dosent save to memory

In [55]:
ex = np.resize(ex,(5,5)) 
ex

array([[0, 1, 2, 3, 4],
       [5, 0, 1, 2, 3],
       [4, 5, 0, 1, 2],
       [3, 4, 5, 0, 1],
       [2, 3, 4, 5, 0]])

In [59]:
ex.ravel()

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3,
       4, 5, 0])

# 21.06.2024 Class 10
> ATTENTION : There are no "," between the values in array!

## Random()?

### Using "randint()" to create 1D array and "N"-D array?
Syntax: randint(start, end, optional: number of outputs)
> "randint()" returns integer

In [ ]:
# Default
# return integer between 1 and 20
print("Default----------------------")
randint1Arr = np.random.randint(1,20)
print(randint1Arr)
print(type(randint1Arr))


In [ ]:
# return array 
# return 27 elements from an array integers between 1 and 20
print("Using optional parameter----------------------")
randint2Arr = np.random.randint(1,20,27)
print(randint2Arr)
print(type(randint2Arr))

Using optional parameter----------------------
[ 9  5 10  5  9 16 19  7  2 16 13 17  9 13  4 16 14  7 19  3 14 14  2  9
 13  6 15]
<class 'numpy.ndarray'>


#### It can be used with reshape() and resize()!

In [ ]:
# array reshaped to 3D array
print("3D array")
randintArrReshaped= randint2Arr.resize(3,3,3) # reshape(1D,2D,3D)
print(randintArrReshaped)

3D array
None


#### Using "rand()" to create 1D  array, 2D & 3D array?
> "rand()" returns float

>Syntax <br>
- If no argument is given a single Python float is returned.<br>
- rand(x) = 1D <br>
- rand(x,y) = 2D <br>
- rand(x,y,z) = 3D_

In [ ]:
# 1D array
randArr1 = np.random.rand(2)    
print("1D",randArr1)

In [ ]:
# 2D array
randArr2 = np.random.rand(3,2)
print("2D",randArr2)

In [ ]:
# 3D array
randArr3 = np.random.rand(3,3,3)
print("3D",randArr3)

### **Choice?**
- Gets the random samples of one dimensional array and return the random samples of numpy array.

- #### Using for numbers?
> **Syntax** : numpy.random.choice(a, size=None, replace=True, p=None)<br>
- **a** : 1D-array or list or tuple that contains the samples
- **size?** : number of elements to be produced in array
- **replace? *False*** : only unique values will be there in array,  ***True*** :Values can be re-used  in array.
- **p?** : probabilities of each element in **"a"** input array.**their addition must be 1, len(p) must be = len(a)**

***Output*** : Return the numpy array of random samples.

In [ ]:
# choice() returning 1D array randomizing element of "ls"
ls = [3,5]
arrChoiceNum = np.random.choice(ls,10)
arrChoiceNum

- #### Using for Str?

In [ ]:
# choice() returning 1D array randomizing element of "lstr"
lstr = ["ram","sham","lakshman","bharat"]

arrChoiceStr = np.random.choice(lstr,10)
arrChoiceStr

> .mean()  .std() 

### **normal()?**

Use the random.normal() method to get a Normal Data Distribution.

> **Syntax**: .normal(loc,scale, size)
- **loc** - (Mean) where the peak of the bell exists.
- **scale** - (Standard Deviation) how flat the graph distribution should be.
- **size** - The shape of the returned array.

In [ ]:
# creating a normal array of 5 mean, std 3 and 5x2x2 dimension

np.random.normal(5,3,(5,2,2)) # normal(mean, std.dev, (x,y,z))

### **binomial()?**

Binomial Distribution is a Discrete Distribution.
> ***Discrete Distribution***:The distribution is defined at **separate** set of events, e.g. a coin toss's result is discrete as it can be only head or tails whereas height of people is **continuous** as it can be 170, 170.1, 170.11 and so on.

It describes the outcome of binary scenarios, e.g. toss of a coin, it will either be head or tails.

> **Syntax** : .binomial(n, p, size)

- **n** - number of trials.
- **p** - probability of occurence of each trial (e.g. for toss of a coin 0.5 each).
- **size** - The shape of the returned array.

In [ ]:
# PROBLEM STATMENT
# vespa comes in 4 colors, we need to find what color was actually sold most
# so we first 100 vespa that we find in trafic

np.random.binomial(4,0.25,(2,50))

#### **Difference Between Normal and Binomial Distribution?**
The main difference is that normal distribution is continous whereas binomial is discrete,<br> but if there are enough data points it will be quite similar to normal distribution with certain loc and scale.
<br>
<br>

### ---------------Doubt      have more understanding of topics above chisquare

### poisson()?
Poisson Distribution is a Discrete Distribution.

It estimates how many times an event can happen in a specified time. e.g. If someone eats twice a day what is the probability he will eat thrice?

It has two parameters:

lam - rate or known number of occurrences e.g. 2 for above problem.

size - The shape of the returned array.

### uniform()?
Used to describe probability where every event has equal chances of occuring.

E.g. Generation of random numbers.

It has three parameters:

a - lower bound - default 0 .0.

b - upper bound - default 1.0.

size - The shape of the returned array.

### logistic()?

Logistic Distribution is used to describe growth.

Used extensively in machine learning in logistic regression, neural networks etc.

It has three parameters:

loc - mean, where the peak is. Default 0.

scale - standard deviation, the flatness of distribution. Default 1.

size - The shape of the returned array.

### multinomial()?

Multinomial distribution is a generalization of binomial distribution.

It describes outcomes of multi-nomial scenarios unlike binomial where scenarios must be only one of two. e.g. Blood type of a population, dice roll outcome.

It has three parameters:

n - number of possible outcomes (e.g. 6 for dice roll).

pvals - list of probabilties of outcomes (e.g. [1/6, 1/6, 1/6, 1/6, 1/6, 1/6] for dice roll).

size - The shape of the returned array.

### exponential()?
Exponential distribution is used for describing time till next event e.g. failure/success etc.

It has two parameters:

scale - inverse of rate ( see lam in poisson distribution ) defaults to 1.0.

size - The shape of the returned array.

### chisquare()?

Chi Square distribution is used as a basis to verify the hypothesis.

It has two parameters:

df - (degree of freedom).

size - The shape of the returned array.

### **.seed()?**
Used to stablize the random generated value
> scope of .seed():
> - .ipynb : Cell it's being used in
> - .py : the whole page under it

In [ ]:
np.random.seed(2)
arrSeed0 = np.random.rand() # not changing with refresh
print("arrSeed0 : ", arrSeed0)

## linespace()?
The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop].

It is similar to NumPy.arange() function but instead of a step, it uses a sample number. 
> **Synatx**: numpy.linspace(start, stop, num=50, endpoint=True , retstep=False, dtype=None, axis=0)
- genrally Start, stop and num parameters are used.

>**Return:**

- ndarray
- step : [float, optional], if restep = True

**Parameters:**

- **start**: [optional] start of interval range. By default start = 0
- **stop**: end of interval range
- **num**: [int, optional] No. of samples to generate
- **retstep**: If True, returts the diff of two consecutive values in the sample array. By default restep = False
    - Using retstep is particularly useful when you need to know the exact spacing between values, which can be important for precise calculations<br> or for understanding the distribution of the generated values.
- **endpoint**: If True, stop is included as the last value. If False, stop is excluded. By default  endpoint=True.
- **dtype**: type of output array
- **axis**: If start and stop are arrays, axis specifies on what axis will the values be added. <br>If axis = **0**, value is added to front, if  axis = **-1** value is added at the end.

In [ ]:
# simple example
lspace1 = np.linspace(0, 1000, 10)
print("lspace1",lspace1)

In [ ]:
# all parameter example
lspace2 = np.linspace(start=0, stop=1000, num=10, endpoint=True, dtype= int )
print("lspace2", lspace2)

## Indexing Matrix?

https://stackoverflow.com/a/16096968

## Boolean Indexing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
arr.shape

In [ ]:
selected_indices = [2, 4, 6, 14]
arr[selected_indices] # prints values in the selected_indices

In [ ]:
bool_arr = np.array([False, True, True, False, True, False, True, True, False, True,False, True, True, False, True])
bool_arr.shape

In [ ]:
bool_arr2 = arr % 2 == 0
bool_arr2

In [ ]:
arr[arr % 2 == 0]

### Get a boolean array which indicates if condition is TRUE or FALSE for the element at that index?

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

condition = arr > 3
print(condition)    # Output: [False False False  True  True]


### Use boolean array to filter elements from original array?

In [ ]:
# Use this boolean array to filter the original array
filtered_arr = arr[condition]
print(filtered_arr)

## Fancy Indexing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
fancy_indexed_arr = arr[indices]
print(fancy_indexed_arr)

## **Array matrix slicing?**

#### 1D array slicing

In [ ]:
# simple in slicing
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[1:5])        # Output: [1 2 3 4]

In [ ]:
#  step slicing

print(arr[::2])        # Output: [0 2 4]

In [ ]:
# combination slicing

print(arr[1:5:2])      # Output: [1 3]

#### 2D array slicing
> here elements refer to single array which constitutes array

In [ ]:
# 1. From the second element, slice elements from index 1 to index 4 (not included)

arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


In [ ]:
# 2. From both elements, slice row from 0 to 2 while skipping the mid row 
#    select columns 1 to 4 and return the 2-D array

arr = np.array([[1, 2, 3, 4, 5 ], 
                [6, 7, 8, 9, 10],
                [5, 7, 8, 2, 3 ]])  #  its a 3*5 matrix

print(arr[0:3:2, 1:4])  # select rows from 0 to 3 with step of 2, column from 1 to 4



In [ ]:
# 3. From both elements, return index 2
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr[0:2, 2])


## Broadcasting
Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes.

### Broadcasting Example
> In this example, the 1D array arr is "broadcast" across each row of the 2D array arr2d.

In [ ]:
arr = np.array([1, 2, 3])
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6]]) 
result = arr + arr2d    # [[1+1, 2+2, 3+3], [1+4, 2+5, 3+6]]
print(result)

## **array to csv ?**

In [ ]:
arr = np.arange(1,11) 
print(arr) 
  
# use the tofile() method  
# and use ',' as a separator 
arr.tofile('delete_this_file.csv', sep = ',')

# **28.06.2024 Class 14**

## arr.resize() vs np.resize(arr)?

arr.resize():
- In-place modification: This method modifies the original array directly.
- Behavior with smaller size: If the new size is smaller, elements at the end of the array are truncated.
- Behavior with larger size: If the new size is larger, the array is padded with zeros (or the specified fill value).
- No return value: This method does not return a new array; it modifies the existing one.

np.resize(arr):
- Creates a new array: This function creates a new array with the specified size.
- Behavior with smaller size: If the new size is smaller, elements from the original array are repeated in a cyclical manner to fill the new array.
- Behavior with larger size: If the new size is larger, elements from the original array are repeated in a cyclical manner to fill the new array.
- Returns a new array: This function returns the resized array.